#!/usr/bin/env bash

if [[ $(basename ${SHELL}) != "zsh" ]]; then
    chsh -s `which zsh`
fi

export XDG_CONFIG_HOME="$HOME/.config"
[[ -d $XDG_CONFIG_HOME ]] || mkdir -p $XDG_CONFIG_HOME

OS=`uname -r`
cwd=`pwd`

if [[ $(basename $cwd) != ".setup" ]]; then
    cd $HOME/.setup
fi

# git submodule init --recursive .

case $OS in
    "Darwin")
        sh @macos/init
        ;;
    "Linux")
        sh @linux/init
        ;;
esac

which antibody > /dev/null
# installing antibody, if its not present
if [[ $? -ne 0 ]]; then
    curl -sL git.io/antibody | sh -s
fi


cd dots-xdg
# apps that support $XDG_CONFIG_HOME
supports_xdg_config=`find . -maxdepth 1 -type d -not -name .`

for dir in $supports_xdg_config; do
    ln -sf $(pwd)/$(basename ${dir}) ${XDG_CONFIG_HOME}/${dir}
done
cd $HOME/.setup

cd dots-no-xdg
# apps which don't support $XDG_CONFIG_HOME
assholes_xdg_config=`find . -maxdepth 1 -not -name .keep -not -name .`
for dir in $assholes_xdg_config; do
    dir_="$(basename ${dir})"
    path="$(pwd)/${dir_}"

    if [[ -d ${dir_} ]]; then
        has_dots=`find ./${dir_} -maxdepth 1 -type f -name "\.*" -not -name .keep -not -name .`

        if [[ $has_dots == "" ]]; then
            ln -sf "${path}" "${HOME}/.${dir_}"
        else
            for file in $has_dots; do
                dotfile=$(basename ${file})
                ln -sf "${path}/${dotfile}" "${HOME}/${dotfile}"
            done
        fi
    else
        ln -sf "${path}" "${HOME}/.${dir_}"
    fi
done
cd $HOME/.setup

source ~/.zprofile 2> /dev/null
source ~/.zshrc 2> /dev/null

antibody bundle < ${ANTIBODY_PLUGS}.txt > ${ANTIBODY_PLUGS}_${OS_}.sh

source ~/.zprofile 2> /dev/null
source ~/.zshrc 2> /dev/null
