#!/bin/bash

#: #############################################################################
#: spaceship-prompt
#: https://denysdovhan.com/spaceship-prompt/
#: #############################################################################
#: https://denysdovhan.com/spaceship-prompt/docs/Options.html
SPACESHIP_PROMPT_ORDER=(
    user      # username
    dir       # cwd
    host      # hostname
    git       # git (git_branch + git_status)
    exec_time # execution time
    battery   # battery
    line_sep  # line break
    vi_mode   # vi-mode indicator
    jobs      # bg jobs indicator
    exit_code # exit code section
    char      # prompt character
)

SPACESHIP_RPROMPT_ORDER=(
    battery   # battery
    conda     # conda
    golang    # golang
    ruby      # ruby
    julia     # julia
    node      # node.js
    dotnet    # .NET
)

SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL="-> "
SPACESHIP_CHAR_SUFFIX=" "

#: simplify for hyper.is prompt
if [[ "${TERM_PROGRAM}" == "Hyper" ]]; then
    SPACESHIP_PROMPT_SEPARATE_LINE=false
    SPACESHIP_DIR_SHOW=false
    SPACESHIP_GIT_BRANCH_SHOW=false
fi