#!/usr/bin/env bash

arch_release=("manjaro" "arch")
debs_release=("debian" "ubuntu")
reds_release=("debian" "ubuntu")

kernel=`uname -r`

installed=0

#: Install on Arch-based systems
for arch in $arch_release; do
    if [[ $kernel | grep -ie $arch ]]; then
        if [[ $? -ne 1 ]]; then
            git clone https://aur.archlinux.org/yay
            cd yay && makepkg -sir; cd ..
            rm -rf yay
        fi
        yay -S -y < @linux/arch

        installed=1
        break
    fi
done

#: Install on Debian-based systems
if [[ $installed -ne 1 ]]; then
    for arch in $debs_release; do
        if [[ $kernel | grep -ie $arch ]]; then
            apt install -y < @linux/debs
            installed=1
            break
        fi
    done
fi

#: Install on RedHat-based systems
if [[ $installed -ne 1 ]]; then
    for arch in $reds_release; do
        if [[ $kernel | grep -ie $arch ]]; then
            dnf install -y < @linux/redh
            installed=1
            break
        fi
    done
fi