prompt_order = [
    "conda", "username", "hostname", "kubernetes", "directory", "git_branch",
    "git_commit", "git_state", "git_status", "hg_branch", "package", "dotnet", "elixir",
    "elm", "golang", "haskell", "java", "nodejs", "php", "python", "ruby", "rust",
    "terraform", "nix_shell", "memory_usage", "aws", "env_var", "crystal",
    "cmd_duration", "line_break", "jobs", "battery", "time", "character",
]

[character]
symbol = "->"
error_symbol = "𝙭"


[conda]
symbol = "🅒 "
color = "bold blue"

[singularity]
symbol = "📦 "