#!/usr/bin/env bash

#: Install Brew
xcode-select --install

which homebrew
# installing homebrew, if its not present
if [[ $? -eq 1 ]]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew bundle install --file=@macos/Brewfile
chsh -s `which zsh`